added kitchensink
minio/mint pull request #329
Opened 2021-08-13 18:17 UTC by eesha-pamula

2021-08-13 18:33 UTC, harshavardhana requested changes

2021-08-13 18:33 UTC, harshavardhana commented on build/kitchensink/install.sh
> +#  Mint (C) 2017 Minio, Inc.
```suggestion
#  Mint (C) 2021 Minio, Inc.
```

2021-08-13 18:33 UTC, harshavardhana commented on run/core/kitchensink/run.sh
> +#  Minio Cloud Storage, (C) 2017 Minio, Inc.
```suggestion
#  Minio Cloud Storage, (C) 2021 Minio, Inc.
```

2021-08-13 18:33 UTC, harshavardhana commented on run/core/kitchensink/run.sh
> +./kitchensink verify $SERVER_ENDPOINT $ACCESS_KEY $SECRET_KEY $BUCKET  1>>"$output_log_file" 2>"$error_log_file"
Are we not deleting the objects after?

2021-08-13 18:54 UTC, eesha-pamula commented on run/core/kitchensink/run.sh
> +./kitchensink verify $SERVER_ENDPOINT $ACCESS_KEY $SECRET_KEY $BUCKET  1>>"$output_log_file" 2>"$error_log_file"
I can delete the objects after. I will add that part.

2021-08-13 22:42 UTC, kannappanr commented on run/core/kitchensink/run.sh
> +
```
rv=$?
if [ "$rv" -ne 0 ]; then
    exit 1
```

2021-08-13 22:43 UTC, kannappanr commented on run/core/kitchensink/run.sh
> +
need to add this before delete

2022-01-20 05:34 UTC, closed without merging

2022-01-20 05:35 UTC, harshavardhana commented
We already incorporated something related to this at https://github.com/minio/minio/tree/master/docs/debugging/s3-check-md5 - used in MinIO CI/CD already.